---
  - include_tasks: 02_firewall.yaml
  - include_tasks: 08_fstab.yaml
  - include_tasks: 17_packages.yaml
  - include_tasks: storage.yaml


-name: 'Accounting, Control ACCT-9626: install the latest version of sysstat'
  package: name=sysstat state=latest

- name: Set a GRUB 2 password for single-user/maintenance modes
  block:
    - blockinfile:
        path: "{{ grub_custom_file }}"
        insertbefore: EOF
        marker: "# {mark} MANAGED BY ANSIBLE-HARDENING"
        block: |
          set superusers="root"
          password_pbkdf2 root {{ security_grub_password_hash }}
        state: present
      notify:
        - update grub config
    - lineinfile:
        path: "{{ grub_linux_file }}"
        regexp: '^CLASS=.*'
        line: 'CLASS="--class gnu-linux --class gnu --class os --unrestricted"'
        state: present
        backrefs: yes
      notify:
        - update grub config


...