---
  # aide: CCE-27096-7
  # xinetd: CCE-27354-0
  # telnet: CCE-27401-9
  # rsh: CCE-27342-5
  # yp*: CCE-27385-4
  # tftp: CCE-80213-2
  # talk: CCE-27432-4
  # sshd: CCE-80215-7
  # avahi: CCE-80338-7
  # UBTU-16-010010
  # UBTU-16-010050

  - name: 'Debian family package installation'
    become: 'yes'
    become_method: sudo
    apt:
      name: "{{ item }}"
      state: latest
      install_recommends: 'no'
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    with_items:
      - "{{ packages_debian }}"
    when: ansible_os_family == "Debian"
    tags:
      - apt
      - section1
      - section1.1

  - name: '1.1.1 Install Updates, Patches and Additional Security Software (Not Scored)'
    apt: update_cache=yes cache_valid_time={{apt_cache_valid_time}}
    tags:
      - section1
      - section1.1
      - section1.1.1