---
- hosts: localhost
  connection: local
  gather_facts: true    # gather OS info that is made available for tasks/roles
  become: yes           # majority of CIS tasks require root
  vars:
    # CIS Controls whitepaper:  http://bit.ly/2mGAmUc
    # Cloudwatch Logs Role configuration
    clamav_daemon_state: started
    clamav_daemon_enabled: yes
    clamav_freshclam_daemon_state: started
    clamav_freshclam_daemon_enabled: yes
    awslogs_setup_region: us-east-1
    # SSH admin local
    sshd_admin_net: [207.244.0.0/24, 207.244.1.0/24]

  roles:
    - common
    - ossec
    - geerlingguy.clamav
    - tartansandal.awslogs-setup
    - k8s-hard-os
    - lynis

  post_tasks:
    - name: "configure awslogs for system log files"
      template:
        src: roles/common/templates/awslogs.conf.j2
        dest: /var/awslogs/etc/awslogs.conf